package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"

	"github.com/vagonaizer/ozon-test-assignment/api/graphql/generated"
	comment_entity "github.com/vagonaizer/ozon-test-assignment/internal/domain/entity/comment"
	post_entity "github.com/vagonaizer/ozon-test-assignment/internal/domain/entity/post"
	"github.com/vagonaizer/ozon-test-assignment/pkg/pagination"
)

// Replies is the resolver for the replies field on Comment.
func (r *commentResolver) Replies(ctx context.Context, obj *generated.Comment, limit *int, cursor *string) (*generated.CommentPage, error) {
	idVal, err := strconv.ParseInt(obj.ID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid comment id: %w", err)
	}
	parentID := comment_entity.CommentID(idVal)

	lim := pagination.DefaultLimit
	if limit != nil {
		lim = *limit
	}
	cur := ""
	if cursor != nil {
		cur = *cursor
	}

	page, err := r.CommentService.ListByParentID(ctx, parentID, lim, cur)
	if err != nil {
		return nil, err
	}

	return commentPageToGQL(page.Items, page.NextCursor, page.HasMore), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, authorID string, title string, content string) (*generated.Post, error) {
	post, err := r.PostService.Create(ctx, authorID, title, content)
	if err != nil {
		return nil, err
	}
	return postToGQL(post), nil
}

// ToggleComments is the resolver for the toggleComments field.
func (r *mutationResolver) ToggleComments(ctx context.Context, postID string, authorID string, enabled bool) (*generated.Post, error) {
	pid, err := post_entity.ParsePostID(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %w", err)
	}

	post, err := r.PostService.ToggleComments(ctx, pid, authorID, enabled)
	if err != nil {
		return nil, err
	}
	return postToGQL(post), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID string, authorID string, parentID *string, text string) (*generated.Comment, error) {
	pid, err := post_entity.ParsePostID(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %w", err)
	}

	var parentCommentID *comment_entity.CommentID
	if parentID != nil {
		n, err := strconv.ParseInt(*parentID, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid parent comment id: %w", err)
		}
		cid := comment_entity.CommentID(n)
		parentCommentID = &cid
	}

	c, err := r.CommentService.Create(ctx, pid, authorID, parentCommentID, text)
	if err != nil {
		return nil, err
	}
	return commentToGQL(c), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int, cursor *string) (*generated.PostPage, error) {
	lim := pagination.DefaultLimit
	if limit != nil {
		lim = *limit
	}
	cur := ""
	if cursor != nil {
		cur = *cursor
	}

	page, err := r.PostService.List(ctx, lim, cur)
	if err != nil {
		return nil, err
	}

	posts := make([]*generated.Post, len(page.Items))
	for i, p := range page.Items {
		posts[i] = postToGQL(p)
	}

	var nextCursor *string
	if page.NextCursor != "" {
		nextCursor = &page.NextCursor
	}

	return &generated.PostPage{
		Posts:      posts,
		NextCursor: nextCursor,
		HasMore:    page.HasMore,
	}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*generated.Post, error) {
	pid, err := post_entity.ParsePostID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %w", err)
	}

	post, err := r.PostService.GetByID(ctx, pid)
	if err != nil {
		return nil, err
	}
	return postToGQL(post), nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string, limit *int, cursor *string) (*generated.CommentPage, error) {
	pid, err := post_entity.ParsePostID(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %w", err)
	}

	lim := pagination.DefaultLimit
	if limit != nil {
		lim = *limit
	}
	cur := ""
	if cursor != nil {
		cur = *cursor
	}

	page, err := r.CommentService.ListByPostID(ctx, pid, lim, cur)
	if err != nil {
		return nil, err
	}

	return commentPageToGQL(page.Items, page.NextCursor, page.HasMore), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *generated.Comment, error) {
	ch, unsubscribe := r.SubManager.Subscribe(comment_entity.PostID(postID))

	out := make(chan *generated.Comment, 16)

	go func() {
		defer unsubscribe()
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case c, ok := <-ch:
				if !ok {
					return
				}
				select {
				case out <- commentToGQL(c):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
